#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "rblox/bytecode"

debug_mode_var = ENV["RBLOX_DEBUG_MODE"]
debug_mode = !debug_mode_var.nil? && !debug_mode_var.empty? && !["0", "false"].include?(debug_mode_var.downcase)

if ARGV.length > 1
  puts "Usage: rblox-bytecode [script]"
  exit 64
elsif ARGV.length == 1
  file_path = ARGV[0]
  contents = File.read(file_path)
  main = Rblox::Bytecode::Main.new
  main.run(contents, debug_mode: debug_mode)
  exit 65 if main.had_error?
  exit 70 if main.had_runtime_error?
else
  Rblox::Bytecode::Repl.new($stdin, Rblox::Bytecode::Main.new, debug_mode: debug_mode).run
end
