# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rublox-parser.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rspec-snapshot"

gem "standard", "~> 1.3"
