#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "rublox/treewalker"

if ARGV.length > 1
  puts "Usage: rublox-treewalker [script]"
  exit 64
elsif ARGV.length == 1
  file_path = ARGV[0]
  contents = File.read(file_path)
  Rublox::TreeWalker::Main.run(contents)
  exit 65 if Rublox::TreeWalker::Main.had_error?
  exit 70 if Rublox::TreeWalker::Main.had_runtime_error?
else
  Rublox::TreeWalker::Repl.new($stdin, Rublox::TreeWalker::Main).run
end
