#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "lox/treewalker"

if ARGV.length > 1
  puts "Usage: lox-treewalker [script]"
  exit 64
elsif ARGV.length == 1
  file_path = ARGV[0]
  contents = File.read(file_path)
  Lox::TreeWalker::Main.run(contents)
  exit 65 if Lox::TreeWalker::Main.had_error?
  exit 70 if Lox::TreeWalker::Main.had_runtime_error?
else
  Lox::TreeWalker::Repl.new($stdin, Lox::TreeWalker::Main).run
end
